name: Say hello

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Gonzalo!"
      - name: Give me the date
        run: |
          date
      - run: ls -l          