name: Say hello

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to deploy to'
          required: true
          default: 'dev'
  
jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Gonzalo!"
      - name: Give me the date
        run: |
          date
      - run: ls -l          