name: Deployment Pipeline

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        #run: npm install --no-audit --no-fund --no-optional
        run: npm ci #Igual que npm install pero mucho más rápido, hace menos comprpobaciones, se basa en la info de pacckage-lock.json
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000
